name: Send Test Email

on:
  schedule:
    - cron: '0 6 * * *'  # Runs at 6:00 AM UTC daily
  workflow_dispatch:

jobs:
  generate-body:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.opening.outputs.output1 }}
      output2: ${{ steps.arXiv.outputs.output2 }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests feedparser

      - name: Write email opening
        id: opening
        run: |
          echo "output1=This is your second round of test emails\n\nHere are the interesting entries from the arXiv\n" >> $GITHUB_OUTPUT

      - name: Check the arXiv
          id: arXiv
          run: |
            result=$(python3 arxiv_query.py authors_list)
            echo "output2<<EOF" >> $GITHUB_OUTPUT
            echo "$result" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT


  send-email:
    runs-on: ubuntu-latest
    needs: generate-body

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install --upgrade pip

      - name: Run Python script to send email
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          OUTPUT1: ${{ needs.generate-body.outputs.output1 }}
          OUTPUT2: ${{ needs.generate-body.outputs.output2 }}
        run: python send_test_email.py "$OUTPUT1" "$OUTPUT2"
